### ISSUE TITLE
 how can i fix it

### ISSUE THREAD

**Issue by ihanhua** [JL-er/RWKV5-infctxLM#1]
Training: |                                                                                                                                         | 0/? [00:00<?, ?it/s]Traceback (most recent call last):
  File "/code/train.py", line 447, in <module>
    trainer.fit(model, data_loader)
  File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 102, in launch
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 989, in _run
    results = self._run_stage()
  File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1035, in _run_stage
    self.fit_loop.run()
  File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 201, in run
    self.on_advance_start()
  File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 341, in on_advance_start
    call._call_callback_hooks(trainer, "on_train_epoch_start")
  File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 208, in _call_callback_hooks
    fn(trainer, trainer.lightning_module, *args, **kwargs)
  File "/code/src/trainer.py", line 144, in on_train_epoch_start
    dataset = trainer.train_dataloader.dataset.datasets
AttributeError: 'MyDataset' object has no attribute 'datasets'

**Comment by Joluck** [comment]
pytorch_lightning==1.9.4
